#ifndef LOGGING_H_INCLUDED
#define LOGGING_H_INCLUDED

#define DEBUG_CMD FALSE
#define DEBUG_I2S FALSE
#define DEBUG_SUBQ FALSE

#define DEBUG_LOGGING_ENABLED (DEBUG_CMD | DEBUG_I2S | DEBUG_SUBQ)

#endif
