#ifndef LOGGING_H_INCLUDED
#define LOGGING_H_INCLUDED

#define DEBUG_CMD 0
#define DEBUG_I2S 0
#define DEBUG_MISC 0
#define DEBUG_SUBQ 0

#define DEBUG_LOGGING_ENABLED (DEBUG_CMD | DEBUG_I2S | DEBUG_MISC | DEBUG_SUBQ)

#endif
