#pragma once

#define DEBUG_CMD 0
#define DEBUG_CUE 0
#define DEBUG_I2S 0
#define DEBUG_MISC 0
#define DEBUG_SUBQ 0

#define DEBUG_LOGGING_ENABLED (DEBUG_CMD | DEBUG_CUE | DEBUG_I2S | DEBUG_MISC | DEBUG_SUBQ)
