#pragma once

#define DEBUG_CMD 0
#define DEBUG_CUE 1
#define DEBUG_I2S 0
#define DEBUG_FILEIO 1
#define DEBUG_MAIN 1
#define DEBUG_MODCHIP 1
#define DEBUG_SUBQ 0

#define DEBUG_LOGGING_ENABLED (DEBUG_CMD || DEBUG_CUE || DEBUG_I2S || DEBUG_FILEIO || DEBUG_MAIN || DEBUG_MODCHIP || DEBUG_SUBQ)
